# -*- coding: utf-8 -*-
"""Copy of Researchplot_AGN_dwarfgalaxy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFx3_iMl1inQjPSHW-XN7Opo97oR3rPU
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv (
    "asu.tsv",
    sep=";",
    skiprows=list(range(54)) + [55, 56],
    skipinitialspace=True
)
df.columns = df.columns.str.strip()
print(df.columns.tolist())



with open("asu.tsv") as f:
    for i, line in enumerate(f):
        print(i, repr(line))
        if i > 15:
            break



df["logM*"] = pd.to_numeric(df["logM*"], errors="coerce")
df["z"] = pd.to_numeric(df["z"], errors="coerce")
df["gMag"] = pd.to_numeric(df["gMag"], errors="coerce")
df["g-r"] = pd.to_numeric(df["g-r"], errors="coerce")

df = df.dropna(subset=["logM*"])

print(f"Loaded {len(df)} galaxies")
print(df[["SDSS", "z", "logM*", "gMag", "g-r"]].head())


dwarf_bh = pd.DataFrame({
    "name":      ["RGG 1", "RGG 9", "RGG 11", "RGG 20", "RGG 21",
                  "RGG 32", "RGG 48", "RGG 118", "RGG 119", "RGG 123",
                  "RGG 127", "Pox 52"],
    "logMstar":  [9.30, 9.24, 9.30, 9.29, 9.45, 8.90, 8.96, 9.43, 9.12, 9.36, 9.36, 8.63],
    "logMBH":    [5.44, 5.00, 5.29, 6.10, 5.80, 5.28, 5.18, 4.70, 5.42, 5.79, 5.21, 5.48],
    "logMBH_err":[0.50]*12,
})

alpha, beta = 7.45, 1.05
logmstar_line = np.linspace(7.5, 12.0, 100)
logmbh_line = alpha + beta * (logmstar_line - 11)


fig1, ax1 = plt.subplots(figsize=(7, 6))
ax1.plot(logmstar_line, logmbh_line, "k--", lw=1.5, label="Reines & Volonteri (2015) AGN relation")
ax1.scatter(dwarf_bh["logMstar"], dwarf_bh["logMBH"], c="crimson", edgecolor="k", s=70, zorder=3, label="Dwarf broad-line AGN")
ax1.errorbar(dwarf_bh["logMstar"], dwarf_bh["logMBH"], yerr=dwarf_bh["logMBH_err"], fmt="none", ecolor="crimson", alpha=0.5, capsize=3, zorder=2)
ax1.set_xlabel(r"$\log_{10}(M_\star / M_\odot)$", fontsize=12)
ax1.set_ylabel(r"$\log_{10}(M_{\rm BH} / M_\odot)$", fontsize=12)
ax1.set_title("Black hole mass vs. stellar mass", fontsize=12)
ax1.legend(fontsize=9, loc="upper left")
ax1.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("mbh_mstar_dwarf.png", dpi=150)
plt.show()



fig2, ax2 = plt.subplots(figsize=(7, 6))
ax2.hist(df["logM*"], bins=15, color="steelblue", edgecolor="k", alpha=0.8)
ax2.set_xlabel(r"$\log_{10}(M_\star / M_\odot)$", fontsize=12)
ax2.set_ylabel("Number of galaxies", fontsize=12)
ax2.set_title(f"Stellar mass distribution (full sample, N={len(df)})", fontsize=12)
ax2.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("mstar_distribution.png", dpi=150)
plt.show()

# plt.tight_layout()
# plt.savefig("mbh_mstar_dwarf_twopanel.png", dpi=150)
# plt.show()

dwarf_bh["predicted_logMBH"] = alpha + beta * (dwarf_bh["logMstar"] - 11)
dwarf_bh["offset_dex"] = dwarf_bh["logMBH"] - dwarf_bh["predicted_logMBH"]

print(dwarf_bh[["name", "logMstar", "logMBH", "predicted_logMBH", "offset_dex"]].to_string(index=False))
print(f"\nMedian offset: {dwarf_bh['offset_dex'].median():.2f} dex")
